Fix text output of `polyswarm search mapping`
Although JSON response is backward compatible, the Error `AttributeError: 'str' object has no attribute 'items'` was triggered because the way the recursive algorithm works, expecting the leaf of the tree structure to be always `{}`, which is not the case anymore.